[package]
name = "rostra-djot"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
jotup = { workspace = true }
rostra-core = { workspace = true }
